# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Build Debug"
lane :test do
  run_tests(
    scheme: "CITest",
    configuration: "Debug",
    device: "iPhone 14 Pro",
    xcodebuild_formatter: "xcpretty --report junit --output 'build/report.junit'",
    code_coverage: true,
    result_bundle_path: "build/result.xcresult",
    result_bundle: true,
    output_directory: "build",
    reset_simulator: true,
  )
  UI.success("test debug😁")
end
