# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR Build & Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  auto-merge:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout ci-script code
        uses: actions/checkout@v4
        with:
          repository: wooky83/ci-script
          token: ${{ secrets.GH_PAT }}
          path: ci-script
      
      - name: Use bash shell
        shell: bash
        run : |
          pushd ci-script
          echo "whynot"
          echo $(pwd)
          echo ${{ github.workspace }}
          popd
      