# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Main Merged Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Main Build
    uses: ./.github/workflows/workflow.yml