# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR Build & Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract Jira issue from commit message
        id: jira
        run: |
          ISSUE_KEY=$(echo '${{ github.event.pull_request.title }}' | grep -o '\[\s*\S*\s*\]')
          ISSUE_KEY=$(echo $ISSUE_KEY | sed 's/ //g')  # Remove spaces
          ISSUE_KEY=${ISSUE_KEY:1:-1}  # Remove the brackets
          echo "::set-output name=issue_key::$ISSUE_KEY"
          
      - name: Transition issue
        if: steps.jira.outputs.issue_key != ''
        id: transition
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.jira.outputs.issue_key }}
          transitionId: 31
        
          # { id: 11, name: 할 일 } transitions issue to '해야 할 일' status.
          # { id: 21, name: 진행 중 } transitions issue to '진행 중' status.
          # { id: 31, name: 검토중 } transitions issue to '검토 중' status.
          # { id: 41, name: 완료 } transitions issue to '완료됨' status.

      - name: Cache RubyGems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: ${{ runner.os }}-gems-
      
      - name: Install dependencies
        run: sh ./bootstrap.sh

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
      
      - name: Danger PreBuild
        run: bundle exec danger --danger_id=prebuild --remove-previous-comments
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Xcode Build & Tests 
        run: bundle exec fastlane test
      
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: 'build/result.xcresult'
        if: success() || failure()
        # ^ This is important because the action will be run
        # even if the test fails in the previous step.

      - name: Danger Postbuild
        run: bundle exec danger --dangerfile=Dangerfile.postbuild --danger_id=postbuild 
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Message
        run: echo "PR Build & Test!"
